### PR TITLE
practicing_pull_request

### PR DESCRIPTION
**Pull request by marwanghalib**
Deliverable for Lecture 4 & 5

### CODE REVIEW

**Review by haiduowad — CHANGES_REQUESTED** [review]
You can add this:

Project Title
One Paragraph of project description goes here

**Review by mchandra5034 — CHANGES_REQUESTED** [review]
As Tariq mentioned , we can include out title and description and then we can merge

**Review by mchandra5034 — APPROVED** [review]

**Comment by xlirate** [comment]
Remove the word should from the last sentence. This is the ReadMe, it should be more sure of itself

**Review by xlirate — APPROVED** [review]
That works, all good.

**Review by haiduowad — APPROVED** [review]

**Pull request merged**
